name: Process New Markdown Files

on:
  push:
    paths:
      - 'kids/**/en/*.md'  # Trigger only on new .md files in en/ directories

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensure the token is not automatically used

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get List of Added Markdown Files
        id: get_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/en/.*\.md$' || true)"
      
      - name: Process Each New Markdown File
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          files="${{ steps.get_files.outputs.files }}"
          if [ -z "$files" ]; then
            echo "No new .md files to process."
            exit 0
          fi
          for file in $files; do
            echo "Processing $file"
            python scripts/process_md.py "$file"
          done
