name: Process New Markdown Files

on:
  push:
    paths:
      - 'kids/**/en/*.md'  # Trigger only on new .md files in en/ directories

permissions:
  contents: write  # Grants write access to repository contents

jobs:
  process-markdown:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for git diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get List of Added Markdown Files
        id: get_files
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/en/.*\.md$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Found files: $files"  # Debugging statement

      - name: Process Each New Markdown File
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GHB_PAT: ${{ secrets.GHB_PAT }}  # Ensure this is set
        run: |
          files="${{ steps.get_files.outputs.files }}"
          if [ -z "$files" ]; then
            echo "No new .md files to process."
            exit 0
          fi
          echo "$files" | while IFS= read -r file; do
            echo "Processing $file"
            python scripts/process_md.py "$file"
          done
